name: CI
on: [push, pull_request]

jobs:
  clean:
    - name: Clean GOPATH
      run: |
        rm -rf $GOPATH/pkg/mod
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Dependency
        run: make setup

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
